# GitHub Pages設定
title: "Vibe Writing実践ガイド"
description: "大学教職員向け生成AI利活用ハンドブックの作成を通じて、Vibe Writingの手法を学ぶ実践的なガイド"
baseurl: "/Getting_Started_with_Vibe_Writing"
url: "https://nahisaho.github.io"

# ビルド設定
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# テーマなし（カスタムレイアウト使用）
theme: null

# 日本語対応
lang: ja

# プラグイン（GitHub Pages標準のみ）
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter

# 相対リンク設定
relative_links:
  enabled: true
  collections: true

# インクルード設定
include:
  - README.md
  - index.html

# デフォルト設定
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "docs"
    values:
      layout: "default"
  - scope:
      path: "docs/guides"
    values:
      layout: "default"

# Sass設定（不要なので無効化）
sass:
  style: compressed